import { Recipe } from "./types";

// Fixed breakfast for quick insulin calc reference:
// Meia de leite + pão Shape Continente + ovo estrelado (2g manteiga)
// ~220 kcal, ~18g HC, ~12g proteína, ~11g gordura
export const FIXED_BREAKFAST = {
  name: "Pequeno-almoço fixo",
  description: "Meia de leite, pão Shape Continente, ovo estrelado (2g manteiga)",
  nutrition: { calories: 220, carbs: 18, protein: 12, fat: 11, fiber: 2 },
};

export const RECIPES: Recipe[] = [
  // === SOPAS (leves, ideais para jantar) ===
  {
    id: "sopa-legumes",
    name: "Sopa de Legumes",
    description: "Sopa cremosa de legumes variados, simples e reconfortante",
    servings: 4,
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Batata", quantity: 2, unit: "unidades", category: "frutas-legumes" },
      { name: "Cenoura", quantity: 2, unit: "unidades", category: "frutas-legumes" },
      { name: "Curgete", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Cebola", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Alho", quantity: 2, unit: "dentes", category: "frutas-legumes" },
      { name: "Azeite", quantity: 2, unit: "colheres de sopa", category: "mercearia" },
      { name: "Sal", quantity: 1, unit: "colher de chá", category: "temperos" },
      { name: "Água", quantity: 1, unit: "litro", category: "outros" },
    ],
    steps: [
      "Descascar e cortar os legumes em pedaços.",
      "Refogar a cebola e o alho no azeite.",
      "Juntar os restantes legumes e a água.",
      "Cozer durante 25 minutos.",
      "Triturar com a varinha mágica.",
    ],
    nutrition: { calories: 120, carbs: 20, protein: 3, fat: 4, fiber: 4 },
    tags: ["sopa", "saudável", "económico"],
  },
  {
    id: "sopa-caldo-verde",
    name: "Caldo Verde",
    description: "O clássico caldo verde português com couve e chouriço",
    servings: 4,
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Batata", quantity: 4, unit: "unidades", category: "frutas-legumes" },
      { name: "Couve portuguesa", quantity: 200, unit: "g", category: "frutas-legumes" },
      { name: "Chouriço", quantity: 1, unit: "unidade", category: "talho-peixaria" },
      { name: "Cebola", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Alho", quantity: 2, unit: "dentes", category: "frutas-legumes" },
      { name: "Azeite", quantity: 3, unit: "colheres de sopa", category: "mercearia" },
      { name: "Sal", quantity: 1, unit: "colher de chá", category: "temperos" },
      { name: "Água", quantity: 1.5, unit: "litros", category: "outros" },
    ],
    steps: [
      "Cozer as batatas com a cebola e alho.",
      "Triturar com a varinha mágica.",
      "Cortar a couve em tiras finas.",
      "Juntar a couve ao caldo e cozer 5 minutos.",
      "Servir com rodelas de chouriço e um fio de azeite.",
    ],
    nutrition: { calories: 210, carbs: 28, protein: 8, fat: 8, fiber: 4 },
    tags: ["sopa", "tradicional"],
  },
  {
    id: "sopa-cenoura-gengibre",
    name: "Sopa de Cenoura e Gengibre",
    description: "Sopa cremosa e aromática de cenoura com gengibre",
    servings: 4,
    prepTimeMinutes: 8,
    cookTimeMinutes: 20,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Cenoura", quantity: 500, unit: "g", category: "frutas-legumes" },
      { name: "Batata", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Cebola", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Gengibre fresco", quantity: 1, unit: "colher de chá", category: "frutas-legumes" },
      { name: "Azeite", quantity: 2, unit: "colheres de sopa", category: "mercearia" },
      { name: "Sal", quantity: 1, unit: "colher de chá", category: "temperos" },
      { name: "Água", quantity: 1, unit: "litro", category: "outros" },
    ],
    steps: [
      "Descascar e cortar as cenouras e a batata.",
      "Refogar a cebola no azeite, juntar o gengibre ralado.",
      "Juntar as cenouras, batata e água.",
      "Cozer 20 minutos e triturar.",
    ],
    nutrition: { calories: 110, carbs: 18, protein: 2, fat: 4, fiber: 4 },
    tags: ["sopa", "saudável"],
  },

  // === ALMOÇO / JANTAR - PRATOS ===
  {
    id: "massa-atum",
    name: "Massa com Atum e Tomate",
    description: "Massa rápida com atum, tomate e azeitonas",
    servings: 2,
    prepTimeMinutes: 5,
    cookTimeMinutes: 15,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Massa esparguete", quantity: 200, unit: "g", category: "mercearia" },
      { name: "Atum em lata", quantity: 2, unit: "latas", category: "mercearia" },
      { name: "Tomate pelado em lata", quantity: 400, unit: "g", category: "mercearia" },
      { name: "Cebola", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Alho", quantity: 2, unit: "dentes", category: "frutas-legumes" },
      { name: "Azeitonas pretas", quantity: 50, unit: "g", category: "mercearia" },
      { name: "Azeite", quantity: 2, unit: "colheres de sopa", category: "mercearia" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
      { name: "Orégãos", quantity: 1, unit: "colher de chá", category: "temperos" },
    ],
    steps: [
      "Cozer a massa al dente.",
      "Refogar cebola e alho no azeite.",
      "Juntar o tomate pelado e deixar apurar 10 minutos.",
      "Adicionar o atum escorrido e as azeitonas.",
      "Misturar com a massa e servir.",
    ],
    nutrition: { calories: 420, carbs: 52, protein: 28, fat: 12, fiber: 4 },
    tags: ["massa", "rápido", "económico"],
  },
  {
    id: "frango-grelhado-salada",
    name: "Frango Grelhado com Salada",
    description: "Peito de frango grelhado com salada fresca e batata-doce",
    servings: 2,
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Peito de frango", quantity: 300, unit: "g", category: "talho-peixaria" },
      { name: "Batata-doce", quantity: 200, unit: "g", category: "frutas-legumes" },
      { name: "Alface", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Tomate", quantity: 2, unit: "unidades", category: "frutas-legumes" },
      { name: "Pepino", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Azeite", quantity: 2, unit: "colheres de sopa", category: "mercearia" },
      { name: "Limão", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
      { name: "Pimenta", quantity: 1, unit: "pitada", category: "temperos" },
      { name: "Alho em pó", quantity: 1, unit: "colher de chá", category: "temperos" },
    ],
    steps: [
      "Temperar o frango com sal, pimenta, alho e limão.",
      "Cozer a batata-doce (pode ser no micro-ondas ~8 min).",
      "Grelhar o frango numa frigideira bem quente.",
      "Preparar a salada com alface, tomate e pepino.",
      "Servir tudo junto, regar com azeite.",
    ],
    nutrition: { calories: 380, carbs: 30, protein: 38, fat: 12, fiber: 5 },
    tags: ["saudável", "proteico"],
  },
  {
    id: "bacalhau-brás",
    name: "Bacalhau à Brás (simplificado)",
    description: "Versão rápida do clássico bacalhau à Brás",
    servings: 2,
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Bacalhau desfiado", quantity: 250, unit: "g", category: "talho-peixaria" },
      { name: "Batata palha", quantity: 100, unit: "g", category: "mercearia" },
      { name: "Ovos", quantity: 4, unit: "unidades", category: "lacticinios" },
      { name: "Cebola", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Alho", quantity: 2, unit: "dentes", category: "frutas-legumes" },
      { name: "Azeite", quantity: 3, unit: "colheres de sopa", category: "mercearia" },
      { name: "Salsa", quantity: 1, unit: "ramo", category: "frutas-legumes" },
      { name: "Azeitonas pretas", quantity: 30, unit: "g", category: "mercearia" },
    ],
    steps: [
      "Refogar a cebola e alho no azeite.",
      "Juntar o bacalhau desfiado e saltear.",
      "Bater os ovos e juntar à frigideira.",
      "Mexer em lume brando até os ovos ficarem cremosos.",
      "Juntar a batata palha no final.",
      "Decorar com salsa e azeitonas.",
    ],
    nutrition: { calories: 450, carbs: 25, protein: 35, fat: 24, fiber: 2 },
    tags: ["tradicional", "proteico"],
  },
  {
    id: "arroz-feijao-legumes",
    name: "Arroz de Feijão com Legumes",
    description: "Arroz reconfortante com feijão encarnado e legumes",
    servings: 4,
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Arroz", quantity: 200, unit: "g", category: "mercearia" },
      { name: "Feijão encarnado (lata)", quantity: 400, unit: "g", category: "mercearia" },
      { name: "Cenoura", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Cebola", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Alho", quantity: 2, unit: "dentes", category: "frutas-legumes" },
      { name: "Tomate", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Coentros", quantity: 1, unit: "ramo", category: "frutas-legumes" },
      { name: "Azeite", quantity: 2, unit: "colheres de sopa", category: "mercearia" },
      { name: "Sal", quantity: 1, unit: "colher de chá", category: "temperos" },
      { name: "Água", quantity: 500, unit: "ml", category: "outros" },
    ],
    steps: [
      "Refogar cebola e alho no azeite.",
      "Juntar a cenoura em cubos e o tomate picado.",
      "Adicionar o arroz, o feijão escorrido e a água.",
      "Cozer ~15 minutos até o arroz estar pronto.",
      "Finalizar com coentros picados.",
    ],
    nutrition: { calories: 340, carbs: 58, protein: 14, fat: 6, fiber: 8 },
    tags: ["económico", "reconfortante"],
  },
  {
    id: "salmao-batata",
    name: "Salmão no Forno com Batata e Brócolos",
    description: "Salmão assado com batata e brócolos — tudo no mesmo tabuleiro",
    servings: 2,
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Salmão (postas)", quantity: 2, unit: "unidades", category: "talho-peixaria" },
      { name: "Batata", quantity: 3, unit: "unidades", category: "frutas-legumes" },
      { name: "Brócolos", quantity: 200, unit: "g", category: "frutas-legumes" },
      { name: "Azeite", quantity: 2, unit: "colheres de sopa", category: "mercearia" },
      { name: "Limão", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Alho", quantity: 2, unit: "dentes", category: "frutas-legumes" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
      { name: "Pimenta", quantity: 1, unit: "pitada", category: "temperos" },
    ],
    steps: [
      "Pré-aquecer o forno a 200°C.",
      "Cortar as batatas em cubos, temperar com azeite e sal.",
      "Levar as batatas ao forno 15 minutos.",
      "Juntar o salmão e os brócolos, regar com limão e azeite.",
      "Assar mais 12-15 minutos.",
    ],
    nutrition: { calories: 420, carbs: 35, protein: 32, fat: 18, fiber: 5 },
    tags: ["saudável", "um-tabuleiro"],
    source: "Inspirado em receitas portuguesas de forno",
  },
  {
    id: "massa-frango-pesto",
    name: "Massa com Frango e Pesto",
    description: "Massa rápida com frango desfiado e molho pesto",
    servings: 2,
    prepTimeMinutes: 5,
    cookTimeMinutes: 15,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Massa penne", quantity: 200, unit: "g", category: "mercearia" },
      { name: "Peito de frango", quantity: 200, unit: "g", category: "talho-peixaria" },
      { name: "Pesto (frasco)", quantity: 3, unit: "colheres de sopa", category: "mercearia" },
      { name: "Tomate cherry", quantity: 100, unit: "g", category: "frutas-legumes" },
      { name: "Azeite", quantity: 1, unit: "colher de sopa", category: "mercearia" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
    ],
    steps: [
      "Cozer a massa al dente.",
      "Cortar o frango em tiras e grelhar na frigideira.",
      "Cortar os tomates cherry ao meio.",
      "Misturar a massa com o frango, pesto e tomates.",
    ],
    nutrition: { calories: 440, carbs: 50, protein: 30, fat: 14, fiber: 3 },
    tags: ["massa", "rápido"],
  },
  {
    id: "omelete-legumes",
    name: "Omelete de Legumes",
    description: "Omelete fofa com legumes variados e salada",
    servings: 2,
    prepTimeMinutes: 5,
    cookTimeMinutes: 10,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Ovos", quantity: 4, unit: "unidades", category: "lacticinios" },
      { name: "Pimento", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Cebola", quantity: 0.5, unit: "unidade", category: "frutas-legumes" },
      { name: "Cogumelos", quantity: 100, unit: "g", category: "frutas-legumes" },
      { name: "Espinafres", quantity: 50, unit: "g", category: "frutas-legumes" },
      { name: "Azeite", quantity: 1, unit: "colher de sopa", category: "mercearia" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
      { name: "Pão integral", quantity: 2, unit: "fatias", category: "padaria" },
    ],
    steps: [
      "Saltear os legumes picados no azeite.",
      "Bater os ovos com sal e juntar aos legumes.",
      "Cozinhar em lume brando, cobrir com tampa.",
      "Dobrar e servir com pão.",
    ],
    nutrition: { calories: 310, carbs: 18, protein: 20, fat: 18, fiber: 3 },
    tags: ["rápido", "económico", "proteico"],
  },
  {
    id: "salada-grao",
    name: "Salada de Grão com Atum",
    description: "Salada fresca de grão-de-bico com atum e legumes",
    servings: 2,
    prepTimeMinutes: 10,
    cookTimeMinutes: 0,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Grão-de-bico (lata)", quantity: 400, unit: "g", category: "mercearia" },
      { name: "Atum em lata", quantity: 2, unit: "latas", category: "mercearia" },
      { name: "Tomate", quantity: 2, unit: "unidades", category: "frutas-legumes" },
      { name: "Cebola", quantity: 0.5, unit: "unidade", category: "frutas-legumes" },
      { name: "Pimento", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Salsa", quantity: 1, unit: "ramo", category: "frutas-legumes" },
      { name: "Azeite", quantity: 3, unit: "colheres de sopa", category: "mercearia" },
      { name: "Vinagre", quantity: 1, unit: "colher de sopa", category: "mercearia" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
    ],
    steps: [
      "Escorrer e lavar o grão-de-bico.",
      "Picar o tomate, cebola, pimento e salsa.",
      "Misturar tudo com o atum escorrido.",
      "Temperar com azeite, vinagre e sal.",
    ],
    nutrition: { calories: 360, carbs: 35, protein: 28, fat: 14, fiber: 8 },
    tags: ["salada", "sem-cozinhar", "económico"],
  },
  {
    id: "arroz-tomate-frango",
    name: "Arroz de Tomate com Frango",
    description: "Arroz de tomate à portuguesa com frango desfiado",
    servings: 4,
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Arroz", quantity: 250, unit: "g", category: "mercearia" },
      { name: "Peito de frango", quantity: 300, unit: "g", category: "talho-peixaria" },
      { name: "Tomate maduro", quantity: 3, unit: "unidades", category: "frutas-legumes" },
      { name: "Cebola", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Alho", quantity: 2, unit: "dentes", category: "frutas-legumes" },
      { name: "Azeite", quantity: 3, unit: "colheres de sopa", category: "mercearia" },
      { name: "Sal", quantity: 1, unit: "colher de chá", category: "temperos" },
      { name: "Pimentão doce", quantity: 1, unit: "colher de chá", category: "temperos" },
      { name: "Água", quantity: 500, unit: "ml", category: "outros" },
    ],
    steps: [
      "Cozer o frango em água com sal, desfiar e reservar.",
      "Refogar cebola e alho no azeite.",
      "Juntar o tomate ralado e o pimentão.",
      "Adicionar o arroz e a água/caldo do frango.",
      "Cozer ~15 minutos, juntar o frango desfiado.",
    ],
    nutrition: { calories: 380, carbs: 50, protein: 25, fat: 8, fiber: 3 },
    tags: ["tradicional", "reconfortante"],
  },
  {
    id: "wrap-frango",
    name: "Wrap de Frango com Legumes",
    description: "Wrap rápido com frango grelhado e legumes frescos",
    servings: 2,
    prepTimeMinutes: 5,
    cookTimeMinutes: 10,
    mealType: ["almoco"],
    ingredients: [
      { name: "Tortilha integral", quantity: 2, unit: "unidades", category: "padaria" },
      { name: "Peito de frango", quantity: 200, unit: "g", category: "talho-peixaria" },
      { name: "Alface", quantity: 4, unit: "folhas", category: "frutas-legumes" },
      { name: "Tomate", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Cenoura", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Mostarda", quantity: 1, unit: "colher de chá", category: "mercearia" },
      { name: "Azeite", quantity: 1, unit: "colher de sopa", category: "mercearia" },
    ],
    steps: [
      "Grelhar o frango temperado, cortar em tiras.",
      "Ralar a cenoura e cortar o tomate.",
      "Montar o wrap: tortilha, mostarda, alface, frango, legumes.",
      "Enrolar e servir.",
    ],
    nutrition: { calories: 350, carbs: 32, protein: 28, fat: 12, fiber: 4 },
    tags: ["rápido"],
  },
  {
    id: "peixe-espada-grelhado",
    name: "Peixe-Espada Grelhado com Arroz e Salada",
    description: "Peixe-espada grelhado com arroz branco e salada mista",
    servings: 2,
    prepTimeMinutes: 5,
    cookTimeMinutes: 20,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Peixe-espada (postas)", quantity: 2, unit: "unidades", category: "talho-peixaria" },
      { name: "Arroz", quantity: 150, unit: "g", category: "mercearia" },
      { name: "Alface", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Tomate", quantity: 2, unit: "unidades", category: "frutas-legumes" },
      { name: "Limão", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Azeite", quantity: 2, unit: "colheres de sopa", category: "mercearia" },
      { name: "Alho", quantity: 1, unit: "dente", category: "frutas-legumes" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
    ],
    steps: [
      "Temperar o peixe com alho, limão e sal.",
      "Cozer o arroz.",
      "Grelhar o peixe na frigideira com azeite.",
      "Preparar a salada e servir tudo junto.",
    ],
    nutrition: { calories: 400, carbs: 45, protein: 30, fat: 12, fiber: 3 },
    tags: ["saudável", "peixe"],
  },

  // === PRATOS LEVES (foco em manutenção/perda de peso) ===
  {
    id: "caldo-peixe-legumes",
    name: "Caldeirada Leve de Peixe",
    description: "Caldeirada ligeira com peixe branco e legumes",
    servings: 2,
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Pescada (lombos)", quantity: 300, unit: "g", category: "talho-peixaria" },
      { name: "Batata", quantity: 2, unit: "unidades", category: "frutas-legumes" },
      { name: "Tomate", quantity: 2, unit: "unidades", category: "frutas-legumes" },
      { name: "Cebola", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Pimento verde", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Coentros", quantity: 1, unit: "ramo", category: "frutas-legumes" },
      { name: "Azeite", quantity: 2, unit: "colheres de sopa", category: "mercearia" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
    ],
    steps: [
      "Cortar legumes em rodelas finas e dispor numa panela.",
      "Colocar o peixe por cima, regar com azeite.",
      "Juntar um pouco de água, tapar e cozer 20 minutos em lume brando.",
      "Servir com coentros picados.",
    ],
    nutrition: { calories: 320, carbs: 28, protein: 30, fat: 10, fiber: 4 },
    tags: ["leve", "peixe", "tradicional"],
  },
  {
    id: "salada-frango-quinoa",
    name: "Salada de Frango com Quinoa",
    description: "Salada proteica e saciante com quinoa e frango grelhado",
    servings: 2,
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    mealType: ["almoco"],
    ingredients: [
      { name: "Peito de frango", quantity: 200, unit: "g", category: "talho-peixaria" },
      { name: "Quinoa", quantity: 100, unit: "g", category: "mercearia" },
      { name: "Pepino", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Tomate cherry", quantity: 100, unit: "g", category: "frutas-legumes" },
      { name: "Abacate", quantity: 0.5, unit: "unidade", category: "frutas-legumes" },
      { name: "Limão", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Azeite", quantity: 2, unit: "colheres de sopa", category: "mercearia" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
    ],
    steps: [
      "Cozer a quinoa segundo as instruções da embalagem.",
      "Grelhar o frango temperado e cortar em tiras.",
      "Cortar pepino, tomates e abacate.",
      "Misturar tudo e temperar com limão e azeite.",
    ],
    nutrition: { calories: 380, carbs: 32, protein: 30, fat: 14, fiber: 6 },
    tags: ["salada", "proteico", "leve"],
  },
  {
    id: "courgette-espaguete",
    name: "Esparguete de Curgete com Frango",
    description: "Alternativa leve à massa com curgete espiralizada",
    servings: 2,
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    mealType: ["jantar"],
    ingredients: [
      { name: "Curgete", quantity: 3, unit: "unidades", category: "frutas-legumes" },
      { name: "Peito de frango", quantity: 200, unit: "g", category: "talho-peixaria" },
      { name: "Tomate cherry", quantity: 150, unit: "g", category: "frutas-legumes" },
      { name: "Alho", quantity: 2, unit: "dentes", category: "frutas-legumes" },
      { name: "Azeite", quantity: 2, unit: "colheres de sopa", category: "mercearia" },
      { name: "Manjericão", quantity: 1, unit: "ramo", category: "frutas-legumes" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
    ],
    steps: [
      "Espiralizar as curgetes (ou cortar em tiras finas com descascador).",
      "Grelhar o frango em tiras e reservar.",
      "Saltear alho no azeite, juntar tomates cortados ao meio.",
      "Adicionar a curgete e saltear 2 minutos. Juntar o frango e manjericão.",
    ],
    nutrition: { calories: 280, carbs: 12, protein: 28, fat: 14, fiber: 4 },
    tags: ["leve", "baixo-hidrato", "rápido"],
  },
  {
    id: "sopa-espinafres-ovo",
    name: "Sopa de Espinafres com Ovo Escalfado",
    description: "Sopa verde nutritiva com ovo escalfado por cima",
    servings: 2,
    prepTimeMinutes: 5,
    cookTimeMinutes: 15,
    mealType: ["jantar"],
    ingredients: [
      { name: "Espinafres", quantity: 200, unit: "g", category: "frutas-legumes" },
      { name: "Batata", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Cebola", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Ovos", quantity: 2, unit: "unidades", category: "lacticinios" },
      { name: "Azeite", quantity: 1, unit: "colher de sopa", category: "mercearia" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
      { name: "Noz-moscada", quantity: 1, unit: "pitada", category: "temperos" },
    ],
    steps: [
      "Cozer batata e cebola em água.",
      "Juntar espinafres e cozer 3 minutos.",
      "Triturar com varinha mágica, temperar com noz-moscada.",
      "Escalfar os ovos na sopa antes de servir.",
    ],
    nutrition: { calories: 200, carbs: 16, protein: 12, fat: 10, fiber: 4 },
    tags: ["sopa", "leve", "proteico"],
  },
  {
    id: "peru-legumes-forno",
    name: "Peru com Legumes no Forno",
    description: "Bife de peru assado com legumes variados — um tabuleiro só",
    servings: 2,
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Bife de peru", quantity: 300, unit: "g", category: "talho-peixaria" },
      { name: "Curgete", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Pimento vermelho", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Cebola", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Cenoura", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Azeite", quantity: 2, unit: "colheres de sopa", category: "mercearia" },
      { name: "Orégãos", quantity: 1, unit: "colher de chá", category: "temperos" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
    ],
    steps: [
      "Pré-aquecer o forno a 200°C.",
      "Cortar legumes em pedaços, temperar com azeite, sal e orégãos.",
      "Dispor no tabuleiro com o peru temperado.",
      "Assar 25 minutos.",
    ],
    nutrition: { calories: 300, carbs: 14, protein: 35, fat: 12, fiber: 4 },
    tags: ["leve", "proteico", "um-tabuleiro"],
  },
  {
    id: "atum-grelhado-salada",
    name: "Bife de Atum Grelhado com Salada",
    description: "Atum fresco grelhado com salada verde e batata-doce",
    servings: 2,
    prepTimeMinutes: 5,
    cookTimeMinutes: 15,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Bife de atum", quantity: 2, unit: "unidades", category: "talho-peixaria" },
      { name: "Batata-doce", quantity: 150, unit: "g", category: "frutas-legumes" },
      { name: "Rúcula", quantity: 80, unit: "g", category: "frutas-legumes" },
      { name: "Tomate", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Limão", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Azeite", quantity: 2, unit: "colheres de sopa", category: "mercearia" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
    ],
    steps: [
      "Cozer a batata-doce cortada em cubos (~10 min).",
      "Grelhar o atum 2 min de cada lado (ficar rosado por dentro).",
      "Preparar salada com rúcula e tomate.",
      "Servir tudo com limão e azeite.",
    ],
    nutrition: { calories: 360, carbs: 22, protein: 35, fat: 14, fiber: 3 },
    tags: ["saudável", "peixe", "proteico"],
  },
];

export function getRecipeById(id: string): Recipe | undefined {
  return RECIPES.find((r) => r.id === id);
}

export function getRecipesByMealType(mealType: string): Recipe[] {
  return RECIPES.filter((r) => r.mealType.includes(mealType as Recipe["mealType"][number]));
}
