import { Recipe } from "./types";

// Fixed breakfast for quick insulin calc reference:
// Meia de leite + pão Shape Continente + ovo estrelado (2g manteiga)
// ~220 kcal, ~18g HC, ~12g proteína, ~11g gordura
export const FIXED_BREAKFAST = {
  name: "Pequeno-almoço fixo",
  description: "Meia de leite, pão Shape Continente, ovo estrelado (2g manteiga)",
  nutrition: { calories: 220, carbs: 18, protein: 12, fat: 11, fiber: 2 },
};

export const RECIPES: Recipe[] = [
  // =============================================
  // === SOPAS ===
  // =============================================
  {
    id: "sopa-legumes",
    name: "Sopa de Legumes",
    description: "Sopa cremosa de legumes variados. Dica: para ficar mais aveludada, junta uma batata extra e tritura bem. Fica melhor no dia seguinte!",
    servings: 4,
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Batata", quantity: 2, unit: "unidades", category: "frutas-legumes" },
      { name: "Cenoura", quantity: 2, unit: "unidades", category: "frutas-legumes" },
      { name: "Curgete", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Cebola", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Alho", quantity: 2, unit: "dentes", category: "frutas-legumes" },
      { name: "Azeite", quantity: 2, unit: "colheres de sopa", category: "mercearia" },
      { name: "Sal", quantity: 1, unit: "colher de chá", category: "temperos" },
      { name: "Água", quantity: 1, unit: "litro", category: "outros" },
    ],
    steps: [
      "Descascar e cortar os legumes em pedaços pequenos (quanto menores, mais rápido cozem).",
      "Num tacho grande, aquecer o azeite em lume médio e refogar a cebola e o alho até ficarem translúcidos (~3 min).",
      "Juntar os restantes legumes e a água. Deixar levantar fervura.",
      "Cozer em lume brando durante 25 minutos com tampa semi-aberta.",
      "Triturar com a varinha mágica até ficar bem cremosa. Retificar o sal.",
    ],
    nutrition: { calories: 120, carbs: 20, protein: 3, fat: 4, fiber: 4 },
    tags: ["sopa", "saudável", "económico"],
  },
  {
    id: "sopa-caldo-verde",
    name: "Caldo Verde",
    description: "O clássico português — cremoso e reconfortante. O segredo é cortar a couve bem fininha e só juntar no final para manter a cor verde viva.",
    servings: 4,
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Batata", quantity: 4, unit: "unidades", category: "frutas-legumes" },
      { name: "Couve portuguesa", quantity: 200, unit: "g", category: "frutas-legumes" },
      { name: "Chouriço", quantity: 1, unit: "unidade", category: "talho-peixaria" },
      { name: "Cebola", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Alho", quantity: 2, unit: "dentes", category: "frutas-legumes" },
      { name: "Azeite", quantity: 3, unit: "colheres de sopa", category: "mercearia" },
      { name: "Sal", quantity: 1, unit: "colher de chá", category: "temperos" },
      { name: "Água", quantity: 1.5, unit: "litros", category: "outros" },
    ],
    steps: [
      "Cozer as batatas com a cebola e alho em água temperada com sal (~20 min).",
      "Triturar com a varinha mágica até obter um caldo cremoso e homogéneo.",
      "Cortar a couve em tiras muito finas (enrolar as folhas e cortar com faca afiada).",
      "Juntar a couve ao caldo e cozer apenas 5 minutos — não mais, para manter a cor e textura.",
      "Cortar o chouriço em rodelas finas e grelhar numa frigideira seca até dourar.",
      "Servir com as rodelas de chouriço por cima e um fio generoso de azeite cru.",
    ],
    nutrition: { calories: 210, carbs: 28, protein: 8, fat: 8, fiber: 4 },
    tags: ["sopa", "tradicional"],
  },
  {
    id: "sopa-cenoura-gengibre",
    name: "Sopa de Cenoura e Gengibre",
    description: "Sopa aromática e quentinha. O gengibre fresco faz toda a diferença — rala na hora para um sabor mais intenso. Excelente para dias frios.",
    servings: 4,
    prepTimeMinutes: 8,
    cookTimeMinutes: 20,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Cenoura", quantity: 500, unit: "g", category: "frutas-legumes" },
      { name: "Batata", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Cebola", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Gengibre fresco", quantity: 1, unit: "colher de chá (ralado)", category: "frutas-legumes" },
      { name: "Azeite", quantity: 2, unit: "colheres de sopa", category: "mercearia" },
      { name: "Sal", quantity: 1, unit: "colher de chá", category: "temperos" },
      { name: "Água", quantity: 1, unit: "litro", category: "outros" },
    ],
    steps: [
      "Descascar e cortar as cenouras e a batata em pedaços pequenos.",
      "Refogar a cebola no azeite em lume médio até amolecer.",
      "Juntar o gengibre fresco ralado na hora e mexer 1 minuto (liberta o aroma).",
      "Adicionar as cenouras, batata e água. Cozer 20 minutos em lume brando.",
      "Triturar bem com a varinha mágica. Ajustar a consistência com mais água se necessário.",
    ],
    nutrition: { calories: 110, carbs: 18, protein: 2, fat: 4, fiber: 4 },
    tags: ["sopa", "saudável"],
  },
  {
    id: "sopa-espinafres-ovo",
    name: "Sopa de Espinafres com Ovo Escalfado",
    description: "Sopa verde e nutritiva coroada com um ovo escalfado cremoso. Dica: para o ovo perfeito, cria um redemoinho suave na sopa antes de o partir para dentro.",
    servings: 2,
    prepTimeMinutes: 5,
    cookTimeMinutes: 15,
    mealType: ["jantar"],
    ingredients: [
      { name: "Espinafres", quantity: 200, unit: "g", category: "frutas-legumes" },
      { name: "Batata", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Cebola", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Ovos", quantity: 2, unit: "unidades", category: "lacticinios" },
      { name: "Azeite", quantity: 1, unit: "colher de sopa", category: "mercearia" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
      { name: "Noz-moscada", quantity: 1, unit: "pitada", category: "temperos" },
    ],
    steps: [
      "Cozer a batata cortada em cubos e a cebola em água temperada (~12 min).",
      "Juntar os espinafres (frescos ou congelados) e cozer apenas 3 minutos.",
      "Triturar com varinha mágica. Temperar com noz-moscada e sal.",
      "Servir na taça e partir um ovo cru para dentro da sopa quente — o calor escalfa o ovo em 3-4 min.",
      "Não mexas depois de pôr o ovo — deixa a clara solidificar enquanto a gema fica cremosa.",
    ],
    nutrition: { calories: 200, carbs: 16, protein: 12, fat: 10, fiber: 4 },
    tags: ["sopa", "leve", "proteico"],
  },
  {
    id: "sopa-abobora",
    name: "Sopa de Abóbora",
    description: "Sopa doce e aveludada, perfeita para o outono. Dica: a abóbora Hokkaido (manteiga) dá a melhor textura cremosa sem precisar de natas.",
    servings: 4,
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Abóbora", quantity: 500, unit: "g", category: "frutas-legumes" },
      { name: "Batata", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Cebola", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Alho", quantity: 1, unit: "dente", category: "frutas-legumes" },
      { name: "Azeite", quantity: 2, unit: "colheres de sopa", category: "mercearia" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
      { name: "Água", quantity: 800, unit: "ml", category: "outros" },
    ],
    steps: [
      "Descascar a abóbora e cortar em cubos (retira as sementes).",
      "Refogar a cebola e o alho no azeite até ficarem macios.",
      "Juntar a abóbora, batata e água. Cozer 20 min em lume brando.",
      "Triturar tudo com a varinha mágica até ficar aveludada.",
      "Servir com um fio de azeite cru e umas sementes de abóbora por cima (opcional).",
    ],
    nutrition: { calories: 130, carbs: 22, protein: 3, fat: 4, fiber: 3 },
    tags: ["sopa", "saudável", "económico"],
  },
  {
    id: "sopa-broculos-alho-frances",
    name: "Sopa de Brócolos e Alho-Francês",
    description: "Sopa verde repleta de fibra e nutrientes. O alho-francês dá um sabor suave e adocicado que equilibra os brócolos. Ótima para quem quer baixar hidratos.",
    servings: 4,
    prepTimeMinutes: 8,
    cookTimeMinutes: 18,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Brócolos", quantity: 400, unit: "g", category: "frutas-legumes" },
      { name: "Alho-francês", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Batata", quantity: 1, unit: "unidade (pequena)", category: "frutas-legumes" },
      { name: "Azeite", quantity: 2, unit: "colheres de sopa", category: "mercearia" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
      { name: "Água", quantity: 800, unit: "ml", category: "outros" },
    ],
    steps: [
      "Lavar e cortar o alho-francês em rodelas (usar a parte branca e verde clara).",
      "Refogar no azeite em lume médio durante 3-4 min até amolecer.",
      "Juntar a batata em cubos, os brócolos cortados e a água.",
      "Cozer 15-18 min até tudo estar macio. Triturar com varinha mágica.",
      "Servir com um fio de azeite cru. Dica: guarda porções individuais no congelador.",
    ],
    nutrition: { calories: 105, carbs: 14, protein: 5, fat: 4, fiber: 5 },
    tags: ["sopa", "saudável", "baixo-hidrato"],
  },
  {
    id: "sopa-feijao-verde",
    name: "Sopa de Feijão Verde",
    description: "Sopa caseira e económica. O feijão verde tem poucos hidratos e muita fibra — ideal para manter a glicemia estável. Rende bem para vários dias.",
    servings: 4,
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Feijão verde", quantity: 300, unit: "g", category: "frutas-legumes" },
      { name: "Batata", quantity: 2, unit: "unidades", category: "frutas-legumes" },
      { name: "Cenoura", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Cebola", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Alho", quantity: 2, unit: "dentes", category: "frutas-legumes" },
      { name: "Azeite", quantity: 2, unit: "colheres de sopa", category: "mercearia" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
      { name: "Água", quantity: 1.2, unit: "litros", category: "outros" },
    ],
    steps: [
      "Cortar as pontas do feijão verde e partir em pedaços de 2-3cm.",
      "Descascar e cortar a batata, cenoura e cebola.",
      "Refogar cebola e alho no azeite. Juntar todos os legumes e a água.",
      "Cozer 25 minutos em lume brando. Triturar (ou deixar com pedaços, ao gosto).",
      "Dica: o feijão verde congelado funciona igualmente bem e poupa tempo.",
    ],
    nutrition: { calories: 115, carbs: 18, protein: 3, fat: 4, fiber: 5 },
    tags: ["sopa", "económico", "baixo-hidrato"],
  },

  // =============================================
  // === PRATOS PRINCIPAIS ===
  // =============================================
  {
    id: "massa-atum",
    name: "Massa com Atum e Tomate",
    description: "Massa rápida e reconfortante. Dica: usa tomate pelado em lata (melhor sabor que tomate fresco fora de época). Deixa o molho apurar bem para concentrar o sabor.",
    servings: 2,
    prepTimeMinutes: 5,
    cookTimeMinutes: 15,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Massa esparguete", quantity: 200, unit: "g", category: "mercearia" },
      { name: "Atum em lata", quantity: 2, unit: "latas", category: "mercearia" },
      { name: "Tomate pelado em lata", quantity: 400, unit: "g", category: "mercearia" },
      { name: "Cebola", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Alho", quantity: 2, unit: "dentes", category: "frutas-legumes" },
      { name: "Azeitonas pretas", quantity: 50, unit: "g", category: "mercearia" },
      { name: "Azeite", quantity: 2, unit: "colheres de sopa", category: "mercearia" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
      { name: "Orégãos", quantity: 1, unit: "colher de chá", category: "temperos" },
    ],
    steps: [
      "Cozer a massa em água com sal até ficar al dente (1-2 min antes do tempo da embalagem).",
      "Enquanto a massa coze: picar a cebola e o alho fino. Refogar no azeite até dourar levemente.",
      "Esmagar o tomate pelado com um garfo e juntar à frigideira. Deixar apurar 10 min em lume médio.",
      "Adicionar o atum escorrido e as azeitonas cortadas ao meio. Temperar com orégãos.",
      "Escorrer a massa (guardar um copo da água da cozedura) e misturar com o molho.",
      "Se o molho estiver seco, juntar um pouco da água da massa para ligar tudo.",
    ],
    nutrition: { calories: 420, carbs: 52, protein: 28, fat: 12, fiber: 4 },
    tags: ["massa", "rápido", "económico"],
  },
  {
    id: "frango-grelhado-salada",
    name: "Frango Grelhado com Salada e Batata-Doce",
    description: "Prato equilibrado e saciante. O segredo do frango suculento: deixa-o à temperatura ambiente 15 min antes e não mexas enquanto grelha — cria uma crosta dourada perfeita.",
    servings: 2,
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Peito de frango", quantity: 300, unit: "g", category: "talho-peixaria" },
      { name: "Batata-doce", quantity: 200, unit: "g", category: "frutas-legumes" },
      { name: "Alface", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Tomate", quantity: 2, unit: "unidades", category: "frutas-legumes" },
      { name: "Pepino", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Azeite", quantity: 2, unit: "colheres de sopa", category: "mercearia" },
      { name: "Limão", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
      { name: "Pimenta", quantity: 1, unit: "pitada", category: "temperos" },
      { name: "Alho em pó", quantity: 1, unit: "colher de chá", category: "temperos" },
    ],
    steps: [
      "Cortar a batata-doce em cubos e cozer no micro-ondas (~8 min) ou em água (~12 min).",
      "Temperar o frango com sal, pimenta, alho em pó e sumo de meio limão. Deixar 10 min.",
      "Aquecer a frigideira em lume alto. Grelhar o frango 5-6 min de cada lado SEM mexer (crosta!).",
      "Deixar o frango repousar 3 min antes de cortar (mantém os sucos dentro).",
      "Preparar a salada com alface lavada, tomate em quartos e pepino em meias-luas.",
      "Servir tudo junto, regar com azeite e o resto do limão.",
    ],
    nutrition: { calories: 380, carbs: 30, protein: 38, fat: 12, fiber: 5 },
    tags: ["saudável", "proteico"],
  },
  {
    id: "bacalhau-bras",
    name: "Bacalhau à Brás (Simplificado)",
    description: "Versão rápida do clássico. Dica crucial: mexe os ovos em lume muito brando e retira do lume ANTES de estarem totalmente cozidos — o calor residual termina a cozedura.",
    servings: 2,
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Bacalhau desfiado", quantity: 250, unit: "g", category: "talho-peixaria" },
      { name: "Batata palha", quantity: 100, unit: "g", category: "mercearia" },
      { name: "Ovos", quantity: 4, unit: "unidades", category: "lacticinios" },
      { name: "Cebola", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Alho", quantity: 2, unit: "dentes", category: "frutas-legumes" },
      { name: "Azeite", quantity: 3, unit: "colheres de sopa", category: "mercearia" },
      { name: "Salsa", quantity: 1, unit: "ramo", category: "frutas-legumes" },
      { name: "Azeitonas pretas", quantity: 30, unit: "g", category: "mercearia" },
    ],
    steps: [
      "Cortar a cebola em meias-luas finas e picar o alho. Refogar no azeite até ficar dourado.",
      "Juntar o bacalhau desfiado (já demolhado!) e saltear 3-4 min.",
      "Bater os ovos com um garfo (não em demasia — é bom ver alguma clara e gema separadas).",
      "Baixar o lume ao mínimo. Verter os ovos sobre o bacalhau e mexer suavemente.",
      "Quando os ovos estiverem AINDA ligeiramente líquidos, retirar do lume e juntar a batata palha.",
      "Decorar com salsa picada e azeitonas. Servir de imediato (a batata palha amolece rápido).",
    ],
    nutrition: { calories: 450, carbs: 25, protein: 35, fat: 24, fiber: 2 },
    tags: ["tradicional", "proteico"],
  },
  {
    id: "arroz-feijao-legumes",
    name: "Arroz de Feijão com Legumes",
    description: "Prato reconfortante e barato. O feijão em lata poupa imenso tempo. Dica: junta os coentros só no final para manter o sabor fresco.",
    servings: 4,
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Arroz", quantity: 200, unit: "g", category: "mercearia" },
      { name: "Feijão encarnado (lata)", quantity: 400, unit: "g", category: "mercearia" },
      { name: "Cenoura", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Cebola", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Alho", quantity: 2, unit: "dentes", category: "frutas-legumes" },
      { name: "Tomate", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Coentros", quantity: 1, unit: "ramo", category: "frutas-legumes" },
      { name: "Azeite", quantity: 2, unit: "colheres de sopa", category: "mercearia" },
      { name: "Sal", quantity: 1, unit: "colher de chá", category: "temperos" },
      { name: "Água", quantity: 500, unit: "ml", category: "outros" },
    ],
    steps: [
      "Picar a cebola e o alho fino. Refogar no azeite até ficarem translúcidos.",
      "Juntar a cenoura em cubos pequenos e o tomate picado (sem pele se preferires).",
      "Adicionar o arroz lavado, o feijão escorrido e a água.",
      "Cozer em lume brando ~15 minutos com tampa, SEM mexer (o arroz fica melhor assim).",
      "Desligar o lume, juntar os coentros picados e deixar repousar 5 min com tampa antes de servir.",
    ],
    nutrition: { calories: 340, carbs: 58, protein: 14, fat: 6, fiber: 8 },
    tags: ["económico", "reconfortante"],
  },
  {
    id: "salmao-batata",
    name: "Salmão no Forno com Batata e Brócolos",
    description: "Tudo num tabuleiro — mínima loiça! O salmão fica perfeito se o tirares do forno quando ainda estiver ligeiramente translúcido no centro (carryover cooking faz o resto).",
    servings: 2,
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Salmão (postas)", quantity: 2, unit: "unidades", category: "talho-peixaria" },
      { name: "Batata", quantity: 3, unit: "unidades", category: "frutas-legumes" },
      { name: "Brócolos", quantity: 200, unit: "g", category: "frutas-legumes" },
      { name: "Azeite", quantity: 2, unit: "colheres de sopa", category: "mercearia" },
      { name: "Limão", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Alho", quantity: 2, unit: "dentes", category: "frutas-legumes" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
      { name: "Pimenta", quantity: 1, unit: "pitada", category: "temperos" },
    ],
    steps: [
      "Pré-aquecer o forno a 200°C. Forrar um tabuleiro com papel vegetal (poupa lavagem).",
      "Cortar as batatas em cubos de ~2cm. Temperar com azeite, sal e alho picado.",
      "Espalhar as batatas no tabuleiro e assar 15 minutos sozinhas.",
      "Retirar, juntar os brócolos em raminhos e o salmão temperado com limão, sal e pimenta.",
      "Assar mais 12-15 minutos. O salmão está pronto quando se desfaz facilmente com um garfo.",
      "Regar com sumo de limão fresco antes de servir.",
    ],
    nutrition: { calories: 420, carbs: 35, protein: 32, fat: 18, fiber: 5 },
    tags: ["saudável", "um-tabuleiro"],
  },
  {
    id: "massa-frango-pesto",
    name: "Massa com Frango e Pesto",
    description: "Pronta em 15 minutos! Usa pesto de frasco para ser mais rápido. Dica: guarda sempre um pouco da água da massa — é o segredo para o molho ficar sedoso e ligado.",
    servings: 2,
    prepTimeMinutes: 5,
    cookTimeMinutes: 15,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Massa penne", quantity: 200, unit: "g", category: "mercearia" },
      { name: "Peito de frango", quantity: 200, unit: "g", category: "talho-peixaria" },
      { name: "Pesto (frasco)", quantity: 3, unit: "colheres de sopa", category: "mercearia" },
      { name: "Tomate cherry", quantity: 100, unit: "g", category: "frutas-legumes" },
      { name: "Azeite", quantity: 1, unit: "colher de sopa", category: "mercearia" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
    ],
    steps: [
      "Cozer a massa al dente. ANTES de escorrer, retirar meio copo da água da cozedura.",
      "Enquanto a massa coze: cortar o frango em tiras finas e grelhar no azeite 5-6 min.",
      "Cortar os tomates cherry ao meio.",
      "Na frigideira do frango, juntar a massa escorrida, o pesto e 2-3 colheres da água da massa.",
      "Mexer tudo em lume brando 1 minuto. A água do amido faz o pesto aderir à massa.",
      "Servir com os tomates cherry frescos por cima.",
    ],
    nutrition: { calories: 440, carbs: 50, protein: 30, fat: 14, fiber: 3 },
    tags: ["massa", "rápido"],
  },
  {
    id: "omelete-legumes",
    name: "Omelete de Legumes",
    description: "Refeição rápida e versátil — usa o que tiveres no frigorífico. Dica: não mexas a omelete depois de verter os ovos; inclina a frigideira para o ovo cru escorrer para os lados.",
    servings: 2,
    prepTimeMinutes: 5,
    cookTimeMinutes: 10,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Ovos", quantity: 4, unit: "unidades", category: "lacticinios" },
      { name: "Pimento", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Cebola", quantity: 0.5, unit: "unidade", category: "frutas-legumes" },
      { name: "Cogumelos", quantity: 100, unit: "g", category: "frutas-legumes" },
      { name: "Espinafres", quantity: 50, unit: "g", category: "frutas-legumes" },
      { name: "Azeite", quantity: 1, unit: "colher de sopa", category: "mercearia" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
      { name: "Pão integral", quantity: 2, unit: "fatias", category: "padaria" },
    ],
    steps: [
      "Cortar os legumes em cubos pequenos (quanto menores, mais rápido cozem).",
      "Saltear os legumes no azeite em lume médio-alto: primeiro a cebola, depois pimento e cogumelos.",
      "Juntar os espinafres no final (murcham em segundos).",
      "Bater os ovos com sal. Espalhar os legumes uniformemente e verter os ovos por cima.",
      "Cozinhar em lume BRANDO, tapado, durante 4-5 min. Não mexer — a tampa faz o vapor cozinhar por cima.",
      "Dobrar ao meio e servir com pão torrado.",
    ],
    nutrition: { calories: 310, carbs: 18, protein: 20, fat: 18, fiber: 3 },
    tags: ["rápido", "económico", "proteico"],
  },
  {
    id: "salada-grao",
    name: "Salada de Grão com Atum",
    description: "Sem cozinhar! Perfeita para dias quentes ou quando não queres sujar loiça. Dica: tempera 10 min antes de servir para os sabores se misturarem bem.",
    servings: 2,
    prepTimeMinutes: 10,
    cookTimeMinutes: 0,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Grão-de-bico (lata)", quantity: 400, unit: "g", category: "mercearia" },
      { name: "Atum em lata", quantity: 2, unit: "latas", category: "mercearia" },
      { name: "Tomate", quantity: 2, unit: "unidades", category: "frutas-legumes" },
      { name: "Cebola", quantity: 0.5, unit: "unidade", category: "frutas-legumes" },
      { name: "Pimento", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Salsa", quantity: 1, unit: "ramo", category: "frutas-legumes" },
      { name: "Azeite", quantity: 3, unit: "colheres de sopa", category: "mercearia" },
      { name: "Vinagre", quantity: 1, unit: "colher de sopa", category: "mercearia" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
    ],
    steps: [
      "Escorrer e lavar bem o grão-de-bico (remove o sabor de lata).",
      "Picar o tomate em cubos, a cebola em meias-luas finas e o pimento em tiras.",
      "Picar a salsa grosseiramente.",
      "Misturar tudo com o atum escorrido numa saladeira.",
      "Temperar generosamente com azeite, vinagre e sal. Mexer bem.",
      "Deixar repousar 10 min antes de servir (os sabores combinam melhor).",
    ],
    nutrition: { calories: 360, carbs: 35, protein: 28, fat: 14, fiber: 8 },
    tags: ["salada", "sem-cozinhar", "económico"],
  },
  {
    id: "arroz-tomate-frango",
    name: "Arroz de Tomate com Frango",
    description: "Clássico português — o arroz fica com um sabor intenso a tomate. O segredo é usar tomate bem maduro e ralar em vez de cortar (liberta mais sumo e sabor).",
    servings: 4,
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Arroz", quantity: 250, unit: "g", category: "mercearia" },
      { name: "Peito de frango", quantity: 300, unit: "g", category: "talho-peixaria" },
      { name: "Tomate maduro", quantity: 3, unit: "unidades", category: "frutas-legumes" },
      { name: "Cebola", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Alho", quantity: 2, unit: "dentes", category: "frutas-legumes" },
      { name: "Azeite", quantity: 3, unit: "colheres de sopa", category: "mercearia" },
      { name: "Sal", quantity: 1, unit: "colher de chá", category: "temperos" },
      { name: "Pimentão doce", quantity: 1, unit: "colher de chá", category: "temperos" },
      { name: "Água", quantity: 500, unit: "ml", category: "outros" },
    ],
    steps: [
      "Cozer o frango inteiro em água com sal ~15 min. Retirar, desfiar e guardar o caldo.",
      "Refogar a cebola picada e o alho no azeite até ficarem dourados.",
      "Ralar os tomates (corta ao meio e rala pela parte cortada — a pele fica na mão). Juntar ao refogado.",
      "Adicionar o pimentão doce e deixar apurar 5 min.",
      "Juntar o arroz lavado e o caldo do frango. Cozer ~15 min em lume brando sem mexer.",
      "Quando o arroz estiver quase pronto, juntar o frango desfiado. Tapar e repousar 5 min.",
    ],
    nutrition: { calories: 380, carbs: 50, protein: 25, fat: 8, fiber: 3 },
    tags: ["tradicional", "reconfortante"],
  },
  {
    id: "wrap-frango",
    name: "Wrap de Frango com Legumes",
    description: "Almoço rápido e transportável. Dica: aquece ligeiramente a tortilha numa frigideira seca antes de montar — fica mais flexível e não parte ao enrolar.",
    servings: 2,
    prepTimeMinutes: 5,
    cookTimeMinutes: 10,
    mealType: ["almoco"],
    ingredients: [
      { name: "Tortilha integral", quantity: 2, unit: "unidades", category: "padaria" },
      { name: "Peito de frango", quantity: 200, unit: "g", category: "talho-peixaria" },
      { name: "Alface", quantity: 4, unit: "folhas", category: "frutas-legumes" },
      { name: "Tomate", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Cenoura", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Mostarda", quantity: 1, unit: "colher de chá", category: "mercearia" },
      { name: "Azeite", quantity: 1, unit: "colher de sopa", category: "mercearia" },
    ],
    steps: [
      "Temperar o frango com sal e pimenta. Grelhar numa frigideira bem quente 5-6 min de cada lado.",
      "Deixar repousar 2 min, depois cortar em tiras finas.",
      "Ralar a cenoura e cortar o tomate em rodelas finas.",
      "Aquecer a tortilha 20 seg numa frigideira seca (fica mais flexível).",
      "Barrar a mostarda, colocar a alface, frango, cenoura e tomate.",
      "Enrolar apertado: dobra os lados primeiro, depois enrola de baixo para cima.",
    ],
    nutrition: { calories: 350, carbs: 32, protein: 28, fat: 12, fiber: 4 },
    tags: ["rápido"],
  },
  {
    id: "peixe-espada-grelhado",
    name: "Peixe-Espada Grelhado com Arroz e Salada",
    description: "Prato simples e saboroso. O peixe-espada é firme e não se desfaz — perfeito para quem está a começar a cozinhar peixe. Limão e alho são tudo o que precisa.",
    servings: 2,
    prepTimeMinutes: 5,
    cookTimeMinutes: 20,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Peixe-espada (postas)", quantity: 2, unit: "unidades", category: "talho-peixaria" },
      { name: "Arroz", quantity: 150, unit: "g", category: "mercearia" },
      { name: "Alface", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Tomate", quantity: 2, unit: "unidades", category: "frutas-legumes" },
      { name: "Limão", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Azeite", quantity: 2, unit: "colheres de sopa", category: "mercearia" },
      { name: "Alho", quantity: 1, unit: "dente", category: "frutas-legumes" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
    ],
    steps: [
      "Temperar o peixe com alho esmagado, sumo de limão e sal. Marinar 10 min enquanto cozinhas o arroz.",
      "Cozer o arroz: 1 chávena arroz, 1.5 chávenas água, pitada de sal. Lume brando 12 min, tampa fechada.",
      "Aquecer a frigideira com azeite em lume alto. Grelhar o peixe 3-4 min de cada lado.",
      "Não mexas enquanto grelha — deixa criar uma crosta dourada antes de virar.",
      "Preparar a salada e servir tudo junto com rodelas de limão.",
    ],
    nutrition: { calories: 400, carbs: 45, protein: 30, fat: 12, fiber: 3 },
    tags: ["saudável", "peixe"],
  },

  // === PRATOS LEVES (foco em manutenção/perda de peso) ===
  {
    id: "caldo-peixe-legumes",
    name: "Caldeirada Leve de Peixe",
    description: "Caldeirada ligeira e saborosa. Dica: dispõe os ingredientes em camadas (legumes em baixo, peixe em cima) e não mexas durante a cozedura — o peixe mantém-se inteiro.",
    servings: 2,
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Pescada (lombos)", quantity: 300, unit: "g", category: "talho-peixaria" },
      { name: "Batata", quantity: 2, unit: "unidades", category: "frutas-legumes" },
      { name: "Tomate", quantity: 2, unit: "unidades", category: "frutas-legumes" },
      { name: "Cebola", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Pimento verde", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Coentros", quantity: 1, unit: "ramo", category: "frutas-legumes" },
      { name: "Azeite", quantity: 2, unit: "colheres de sopa", category: "mercearia" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
    ],
    steps: [
      "Cortar as batatas em rodelas finas (~3mm), a cebola em meias-luas e o tomate em rodelas.",
      "Numa panela, dispor em camadas: cebola → batata → tomate → pimento → peixe por cima.",
      "Regar com azeite e juntar apenas um dedo de água (o peixe e legumes libertam líquido).",
      "Tapar e cozer em lume brando 20 min. NÃO mexer — apenas agitar a panela suavemente.",
      "Servir com coentros picados por cima e pão para molhar no caldo (opcional).",
    ],
    nutrition: { calories: 320, carbs: 28, protein: 30, fat: 10, fiber: 4 },
    tags: ["leve", "peixe", "tradicional"],
  },
  {
    id: "salada-frango-quinoa",
    name: "Salada de Frango com Quinoa",
    description: "Salada proteica que sacia a sério. A quinoa tem proteína completa e fibra. Dica: lava sempre a quinoa antes de cozer (remove a saponina que dá sabor amargo).",
    servings: 2,
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    mealType: ["almoco"],
    ingredients: [
      { name: "Peito de frango", quantity: 200, unit: "g", category: "talho-peixaria" },
      { name: "Quinoa", quantity: 100, unit: "g", category: "mercearia" },
      { name: "Pepino", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Tomate cherry", quantity: 100, unit: "g", category: "frutas-legumes" },
      { name: "Abacate", quantity: 0.5, unit: "unidade", category: "frutas-legumes" },
      { name: "Limão", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Azeite", quantity: 2, unit: "colheres de sopa", category: "mercearia" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
    ],
    steps: [
      "Lavar a quinoa em água corrente durante 30 seg (importante para remover o amargor).",
      "Cozer a quinoa: 1 parte quinoa, 2 partes água, 12-15 min até a água absorver. Soltar com garfo.",
      "Grelhar o frango temperado e cortar em tiras finas depois de repousar 2 min.",
      "Cortar o pepino em meias-luas, os tomates ao meio e o abacate em cubos.",
      "Misturar tudo numa saladeira. Temperar com limão e azeite.",
      "Dica: prepara a quinoa no domingo e usa durante a semana (aguenta 5 dias no frio).",
    ],
    nutrition: { calories: 380, carbs: 32, protein: 30, fat: 14, fiber: 6 },
    tags: ["salada", "proteico", "leve"],
  },
  {
    id: "courgette-espaguete",
    name: "Esparguete de Curgete com Frango",
    description: "Alternativa low-carb à massa — a curgete espiralizada absorve os sabores do molho. Dica: não cozinhes a curgete mais de 2 min ou fica aguada. Salta-a em lume alto.",
    servings: 2,
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    mealType: ["jantar"],
    ingredients: [
      { name: "Curgete", quantity: 3, unit: "unidades", category: "frutas-legumes" },
      { name: "Peito de frango", quantity: 200, unit: "g", category: "talho-peixaria" },
      { name: "Tomate cherry", quantity: 150, unit: "g", category: "frutas-legumes" },
      { name: "Alho", quantity: 2, unit: "dentes", category: "frutas-legumes" },
      { name: "Azeite", quantity: 2, unit: "colheres de sopa", category: "mercearia" },
      { name: "Manjericão", quantity: 1, unit: "ramo", category: "frutas-legumes" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
    ],
    steps: [
      "Espiralizar as curgetes (ou cortar em tiras finas com um descascador — funciona bem!).",
      "Cortar o frango em tiras finas e grelhar no azeite em lume alto 5-6 min. Reservar.",
      "Na mesma frigideira, saltear o alho picado 30 seg. Juntar os tomates cortados ao meio.",
      "Saltear 2 min até os tomates amolecerem ligeiramente. Juntar a curgete.",
      "Saltear a curgete APENAS 1-2 min em lume alto (lume brando = curgete aguada).",
      "Juntar o frango e o manjericão rasgado. Servir imediatamente.",
    ],
    nutrition: { calories: 280, carbs: 12, protein: 28, fat: 14, fiber: 4 },
    tags: ["leve", "baixo-hidrato", "rápido"],
  },
  {
    id: "peru-legumes-forno",
    name: "Peru com Legumes no Forno",
    description: "Um tabuleiro, zero stress. O peru é mais magro que o frango e fica suculento se não ultrapassares os 25 min de forno. Corta os legumes do mesmo tamanho para cozinharem uniformemente.",
    servings: 2,
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Bife de peru", quantity: 300, unit: "g", category: "talho-peixaria" },
      { name: "Curgete", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Pimento vermelho", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Cebola", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Cenoura", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Azeite", quantity: 2, unit: "colheres de sopa", category: "mercearia" },
      { name: "Orégãos", quantity: 1, unit: "colher de chá", category: "temperos" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
    ],
    steps: [
      "Pré-aquecer o forno a 200°C. Forrar o tabuleiro com papel vegetal.",
      "Cortar TODOS os legumes em pedaços do mesmo tamanho (~2cm) para cozinharem ao mesmo tempo.",
      "Temperar os legumes e o peru com azeite, sal e orégãos numa taça.",
      "Dispor no tabuleiro: legumes espalhados, peru por cima (não empilhar).",
      "Assar 25 minutos. A meio (~12 min) virar o peru para dourar dos dois lados.",
      "Está pronto quando o peru estiver dourado por fora e os legumes caramelizados nas pontas.",
    ],
    nutrition: { calories: 300, carbs: 14, protein: 35, fat: 12, fiber: 4 },
    tags: ["leve", "proteico", "um-tabuleiro"],
  },
  {
    id: "atum-grelhado-salada",
    name: "Bife de Atum Grelhado com Salada",
    description: "Atum fresco grelhado — o truque é NÃO cozinhar demais. 2 min de cada lado e fica rosado por dentro, suculento e com sabor a mar. A batata-doce dá os hidratos necessários.",
    servings: 2,
    prepTimeMinutes: 5,
    cookTimeMinutes: 15,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Bife de atum", quantity: 2, unit: "unidades", category: "talho-peixaria" },
      { name: "Batata-doce", quantity: 150, unit: "g", category: "frutas-legumes" },
      { name: "Rúcula", quantity: 80, unit: "g", category: "frutas-legumes" },
      { name: "Tomate", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Limão", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Azeite", quantity: 2, unit: "colheres de sopa", category: "mercearia" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
    ],
    steps: [
      "Cozer a batata-doce cortada em cubos (~10 min em água ou 5 min no micro-ondas).",
      "Secar o atum com papel de cozinha e temperar com sal e pimenta.",
      "Frigideira BEM quente com um fio de azeite. Colocar o atum e NÃO mexer.",
      "2 minutos de cada lado — deve ficar com crosta por fora e rosado/cru por dentro.",
      "Preparar a salada com rúcula e tomate. Servir com limão e azeite.",
      "Dica: se preferires bem passado, 3-4 min de cada lado, mas fica mais seco.",
    ],
    nutrition: { calories: 360, carbs: 22, protein: 35, fat: 14, fiber: 3 },
    tags: ["saudável", "peixe", "proteico"],
  },

  // === NOVOS PRATOS PRINCIPAIS ===
  {
    id: "frango-paprica-arroz",
    name: "Frango com Páprica e Arroz",
    description: "O pimentão doce/páprica dá uma cor linda e um sabor fumado ao frango. Dica: usa coxas desossadas em vez de peito — ficam mais suculentas e são mais baratas.",
    servings: 2,
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Coxas de frango desossadas", quantity: 300, unit: "g", category: "talho-peixaria" },
      { name: "Arroz", quantity: 150, unit: "g", category: "mercearia" },
      { name: "Pimento vermelho", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Cebola", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Alho", quantity: 2, unit: "dentes", category: "frutas-legumes" },
      { name: "Tomate pelado (lata)", quantity: 200, unit: "g", category: "mercearia" },
      { name: "Pimentão doce", quantity: 1, unit: "colher de sopa", category: "temperos" },
      { name: "Azeite", quantity: 2, unit: "colheres de sopa", category: "mercearia" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
      { name: "Água", quantity: 300, unit: "ml", category: "outros" },
    ],
    steps: [
      "Cortar o frango em pedaços e temperar com pimentão doce, sal e alho picado.",
      "Aquecer o azeite numa frigideira funda. Selar o frango 2-3 min de cada lado até dourar.",
      "Retirar o frango. Na mesma frigideira, refogar a cebola e o pimento em tiras.",
      "Juntar o tomate pelado esmagado e cozinhar 5 min.",
      "Voltar a colocar o frango, juntar a água e o arroz lavado. Tapar e cozer 15 min.",
      "O arroz fica com uma cor laranja bonita. Deixar repousar 5 min com tampa antes de servir.",
    ],
    nutrition: { calories: 420, carbs: 48, protein: 30, fat: 12, fiber: 3 },
    tags: ["reconfortante", "tradicional"],
  },
  {
    id: "dourada-forno-batata",
    name: "Dourada no Forno com Batata",
    description: "Peixe no forno à portuguesa — simples e elegante. A dourada é das melhores escolhas: sabor suave e preço acessível. Pede na peixaria para limpar o peixe.",
    servings: 2,
    prepTimeMinutes: 10,
    cookTimeMinutes: 30,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Dourada", quantity: 1, unit: "unidade (grande)", category: "talho-peixaria" },
      { name: "Batata", quantity: 3, unit: "unidades", category: "frutas-legumes" },
      { name: "Cebola", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Tomate", quantity: 2, unit: "unidades", category: "frutas-legumes" },
      { name: "Pimento verde", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Limão", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Azeite", quantity: 3, unit: "colheres de sopa", category: "mercearia" },
      { name: "Alho", quantity: 2, unit: "dentes", category: "frutas-legumes" },
      { name: "Sal grosso", quantity: 1, unit: "colher de chá", category: "temperos" },
    ],
    steps: [
      "Pré-aquecer o forno a 200°C.",
      "Cortar as batatas em rodelas finas, a cebola em meias-luas, o tomate em rodelas.",
      "Dispor as batatas num tabuleiro, temperadas com azeite e sal. Cobrir com cebola e tomate.",
      "Fazer 3 cortes transversais na dourada e inserir rodelas de limão e alho.",
      "Colocar o peixe sobre os legumes. Regar com azeite e sumo de limão.",
      "Assar 30 min, regando com o molho do tabuleiro a meio da cozedura.",
    ],
    nutrition: { calories: 380, carbs: 32, protein: 28, fat: 15, fiber: 4 },
    tags: ["peixe", "tradicional", "um-tabuleiro"],
  },
  {
    id: "salada-lentilhas",
    name: "Salada Morna de Lentilhas com Ovo",
    description: "Lentilhas são riquíssimas em fibra e proteína vegetal — mantêm a glicemia muito estável. Servir morna é o segredo: absorve melhor o tempero que fria.",
    servings: 2,
    prepTimeMinutes: 5,
    cookTimeMinutes: 20,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Lentilhas (lata ou secas)", quantity: 250, unit: "g", category: "mercearia" },
      { name: "Ovos", quantity: 2, unit: "unidades", category: "lacticinios" },
      { name: "Cenoura", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Tomate", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Cebola roxa", quantity: 0.5, unit: "unidade", category: "frutas-legumes" },
      { name: "Salsa", quantity: 1, unit: "ramo", category: "frutas-legumes" },
      { name: "Azeite", quantity: 2, unit: "colheres de sopa", category: "mercearia" },
      { name: "Vinagre de vinho", quantity: 1, unit: "colher de sopa", category: "mercearia" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
      { name: "Cominhos", quantity: 0.5, unit: "colher de chá", category: "temperos" },
    ],
    steps: [
      "Se usares lentilhas secas, cozer em água 18-20 min. Se em lata, escorrer e aquecer.",
      "Cozer os ovos 7 min (gema semi-líquida) ou 10 min (gema dura). Arrefecer em água fria.",
      "Picar a cenoura em cubos pequenos, o tomate em cubos, e a cebola roxa em meias-luas finas.",
      "Misturar as lentilhas mornas com os legumes, salsa picada, azeite, vinagre e cominhos.",
      "Servir com o ovo cortado ao meio por cima. Temperar com sal e azeite a gosto.",
    ],
    nutrition: { calories: 340, carbs: 34, protein: 22, fat: 14, fiber: 10 },
    tags: ["leve", "proteico", "saudável"],
  },
  {
    id: "bifanas",
    name: "Bifanas com Salada",
    description: "Clássico português adaptado para ser mais leve. O segredo da bifana perfeita é a carne bem fina e a marinada com vinho branco, alho e louro — prepara no dia anterior se puderes.",
    servings: 2,
    prepTimeMinutes: 15,
    cookTimeMinutes: 10,
    mealType: ["almoco"],
    ingredients: [
      { name: "Bifanas de porco (finas)", quantity: 300, unit: "g", category: "talho-peixaria" },
      { name: "Pão (tipo papo-seco)", quantity: 2, unit: "unidades", category: "padaria" },
      { name: "Vinho branco", quantity: 100, unit: "ml", category: "mercearia" },
      { name: "Alho", quantity: 3, unit: "dentes", category: "frutas-legumes" },
      { name: "Louro", quantity: 2, unit: "folhas", category: "temperos" },
      { name: "Pimentão doce", quantity: 1, unit: "colher de chá", category: "temperos" },
      { name: "Azeite", quantity: 1, unit: "colher de sopa", category: "mercearia" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
      { name: "Alface", quantity: 4, unit: "folhas", category: "frutas-legumes" },
      { name: "Tomate", quantity: 1, unit: "unidade", category: "frutas-legumes" },
    ],
    steps: [
      "Marinar a carne com vinho branco, alho esmagado, louro, pimentão e sal (mín. 30 min, ideal de véspera).",
      "Aquecer uma frigideira grande com azeite em lume alto.",
      "Retirar a carne da marinada (guardar o líquido) e grelhar 1-2 min de cada lado.",
      "Retirar a carne. Deitar a marinada na frigideira e deixar reduzir 2-3 min.",
      "Colocar as bifanas no pão, regar com o molho da frigideira.",
      "Servir com salada de alface e tomate ao lado (equilibra a refeição).",
    ],
    nutrition: { calories: 450, carbs: 35, protein: 32, fat: 18, fiber: 3 },
    tags: ["tradicional", "rápido"],
  },
  {
    id: "tofu-salteado-legumes",
    name: "Tofu Salteado com Legumes e Arroz",
    description: "Alternativa vegetariana rica em proteína. O truque: pressiona o tofu com papel de cozinha antes de cozinhar (retira água = melhor textura e sabor ao saltear).",
    servings: 2,
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Tofu firme", quantity: 250, unit: "g", category: "mercearia" },
      { name: "Arroz", quantity: 150, unit: "g", category: "mercearia" },
      { name: "Brócolos", quantity: 150, unit: "g", category: "frutas-legumes" },
      { name: "Cenoura", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Molho de soja", quantity: 2, unit: "colheres de sopa", category: "mercearia" },
      { name: "Gengibre fresco", quantity: 1, unit: "colher de chá (ralado)", category: "frutas-legumes" },
      { name: "Alho", quantity: 2, unit: "dentes", category: "frutas-legumes" },
      { name: "Azeite", quantity: 2, unit: "colheres de sopa", category: "mercearia" },
    ],
    steps: [
      "Escorrer o tofu e pressionar entre papel de cozinha 10 min (retira água para melhor textura).",
      "Cortar o tofu em cubos de 2cm. Cozer o arroz.",
      "Aquecer o azeite em lume ALTO. Dourar o tofu 3-4 min sem mexer muito (criar crosta).",
      "Retirar o tofu. Na mesma frigideira/wok, saltear cenoura em palitos e brócolos 3 min.",
      "Juntar alho e gengibre ralados, saltear 30 seg.",
      "Voltar a juntar o tofu, regar com molho de soja e mexer 1 min. Servir sobre o arroz.",
    ],
    nutrition: { calories: 380, carbs: 45, protein: 20, fat: 14, fiber: 5 },
    tags: ["vegetariano", "saudável"],
  },
  {
    id: "massa-legumes-azeite",
    name: "Massa Aglio e Olio com Legumes",
    description: "Massa italiana simples — alho, azeite e malagueta é tudo. Juntámos legumes para ficar mais completa. A chave é dourar o alho SEM queimar (fica amargo se escurecer).",
    servings: 2,
    prepTimeMinutes: 5,
    cookTimeMinutes: 15,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Massa esparguete", quantity: 200, unit: "g", category: "mercearia" },
      { name: "Alho", quantity: 4, unit: "dentes", category: "frutas-legumes" },
      { name: "Brócolos", quantity: 150, unit: "g", category: "frutas-legumes" },
      { name: "Tomate cherry", quantity: 100, unit: "g", category: "frutas-legumes" },
      { name: "Azeite", quantity: 4, unit: "colheres de sopa", category: "mercearia" },
      { name: "Malagueta seca", quantity: 1, unit: "pitada (flocos)", category: "temperos" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
      { name: "Salsa", quantity: 1, unit: "ramo", category: "frutas-legumes" },
    ],
    steps: [
      "Cozer a massa al dente. Nos últimos 3 min, juntar os brócolos à água da massa.",
      "Enquanto a massa coze: laminar o alho fino. Aquecer o azeite em lume MÉDIO-baixo.",
      "Dourar o alho suavemente no azeite 2-3 min — deve ficar dourado claro, NÃO escuro.",
      "Juntar a malagueta e os tomates cherry cortados ao meio.",
      "Escorrer a massa e brócolos (guardar 1 copo de água). Juntar ao alho.",
      "Adicionar água da massa aos poucos, mexer bem. A salsa picada vai por cima.",
    ],
    nutrition: { calories: 400, carbs: 52, protein: 12, fat: 16, fiber: 4 },
    tags: ["massa", "rápido", "vegetariano"],
  },
  {
    id: "salmao-teriyaki",
    name: "Salmão com Molho Teriyaki e Legumes",
    description: "Sabor asiático com ingredientes simples. O molho teriyaki caseiro é fácil: molho de soja + mel + gengibre. O salmão fica com uma crosta caramelizada irresistível.",
    servings: 2,
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Salmão (postas)", quantity: 2, unit: "unidades", category: "talho-peixaria" },
      { name: "Molho de soja", quantity: 3, unit: "colheres de sopa", category: "mercearia" },
      { name: "Mel", quantity: 1, unit: "colher de sopa", category: "mercearia" },
      { name: "Gengibre fresco", quantity: 1, unit: "colher de chá (ralado)", category: "frutas-legumes" },
      { name: "Alho", quantity: 1, unit: "dente", category: "frutas-legumes" },
      { name: "Brócolos", quantity: 200, unit: "g", category: "frutas-legumes" },
      { name: "Arroz", quantity: 150, unit: "g", category: "mercearia" },
      { name: "Azeite", quantity: 1, unit: "colher de sopa", category: "mercearia" },
    ],
    steps: [
      "Misturar molho de soja, mel, gengibre ralado e alho picado para o molho teriyaki.",
      "Marinar o salmão no molho 10 min (enquanto cozinhas o arroz e os brócolos).",
      "Cozer o arroz. Cozer os brócolos al dente em água a ferver 3-4 min.",
      "Aquecer a frigideira com azeite em lume médio-alto.",
      "Retirar o salmão da marinada e grelhar 3 min de cada lado.",
      "Deitar o resto da marinada na frigideira e deixar caramelizar 1 min. Regar sobre o salmão.",
    ],
    nutrition: { calories: 440, carbs: 48, protein: 32, fat: 14, fiber: 3 },
    tags: ["peixe", "saudável"],
  },
  {
    id: "hamburguer-caseiro",
    name: "Hambúrguer Caseiro de Frango",
    description: "Muito mais saudável que fast food e igualmente saboroso. Dica: não comprimas o hambúrguer com a espátula enquanto grelha — perde todos os sucos e fica seco.",
    servings: 2,
    prepTimeMinutes: 15,
    cookTimeMinutes: 10,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Frango picado", quantity: 300, unit: "g", category: "talho-peixaria" },
      { name: "Pão de hambúrguer integral", quantity: 2, unit: "unidades", category: "padaria" },
      { name: "Alface", quantity: 4, unit: "folhas", category: "frutas-legumes" },
      { name: "Tomate", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Cebola roxa", quantity: 0.5, unit: "unidade", category: "frutas-legumes" },
      { name: "Mostarda", quantity: 1, unit: "colher de chá", category: "mercearia" },
      { name: "Salsa", quantity: 1, unit: "colher de sopa (picada)", category: "frutas-legumes" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
      { name: "Pimenta", quantity: 1, unit: "pitada", category: "temperos" },
      { name: "Azeite", quantity: 1, unit: "colher de sopa", category: "mercearia" },
    ],
    steps: [
      "Misturar o frango picado com salsa, sal, pimenta e mostarda. Formar 2 hambúrgueres.",
      "Fazer uma pequena concavidade no centro de cada um (evita que inchem no centro).",
      "Aquecer a frigideira em lume médio-alto com azeite.",
      "Grelhar 4-5 min de cada lado. NÃO pressionar com espátula (perde sucos!).",
      "Tostar o pão na mesma frigideira 30 seg.",
      "Montar: pão, alface, hambúrguer, tomate em rodela, cebola roxa em anéis.",
    ],
    nutrition: { calories: 400, carbs: 30, protein: 35, fat: 15, fiber: 4 },
    tags: ["rápido", "proteico"],
  },
  {
    id: "risotto-cogumelos",
    name: "Risotto de Cogumelos (Simplificado)",
    description: "Risotto cremoso sem complicações. O segredo: junta o caldo quente aos poucos e mexe sempre. A paciência é recompensada com uma textura incrivelmente cremosa.",
    servings: 2,
    prepTimeMinutes: 5,
    cookTimeMinutes: 25,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Arroz arbóreo ou carolino", quantity: 200, unit: "g", category: "mercearia" },
      { name: "Cogumelos", quantity: 200, unit: "g", category: "frutas-legumes" },
      { name: "Cebola", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Alho", quantity: 2, unit: "dentes", category: "frutas-legumes" },
      { name: "Vinho branco", quantity: 50, unit: "ml", category: "mercearia" },
      { name: "Caldo de legumes", quantity: 700, unit: "ml", category: "mercearia" },
      { name: "Azeite", quantity: 2, unit: "colheres de sopa", category: "mercearia" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
      { name: "Salsa", quantity: 1, unit: "ramo", category: "frutas-legumes" },
    ],
    steps: [
      "Aquecer o caldo num tacho à parte (deve estar quente quando o adicionas ao arroz).",
      "Refogar a cebola e alho picados no azeite. Juntar os cogumelos fatiados e saltear 3 min.",
      "Juntar o arroz (NÃO lavar) e mexer 1 min para o arroz absorver a gordura.",
      "Deitar o vinho branco e mexer até evaporar.",
      "Adicionar o caldo quente uma concha de cada vez, mexendo sempre. Só juntar mais quando absorver.",
      "Após ~18 min o arroz deve estar cremoso mas com ligeiro bite. Temperar e servir com salsa.",
    ],
    nutrition: { calories: 380, carbs: 55, protein: 10, fat: 10, fiber: 3 },
    tags: ["reconfortante", "vegetariano"],
  },
  {
    id: "frango-limao-ervas",
    name: "Frango ao Limão com Ervas e Batata",
    description: "Frango suculento e aromático. A marinada de limão amacia a carne e dá um sabor fresco. Dica: marinar mín. 30 min (de véspera é ainda melhor).",
    servings: 2,
    prepTimeMinutes: 10,
    cookTimeMinutes: 30,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Coxas de frango", quantity: 4, unit: "unidades", category: "talho-peixaria" },
      { name: "Batata", quantity: 3, unit: "unidades", category: "frutas-legumes" },
      { name: "Limão", quantity: 2, unit: "unidades", category: "frutas-legumes" },
      { name: "Alho", quantity: 3, unit: "dentes", category: "frutas-legumes" },
      { name: "Azeite", quantity: 3, unit: "colheres de sopa", category: "mercearia" },
      { name: "Orégãos", quantity: 1, unit: "colher de chá", category: "temperos" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
      { name: "Pimenta", quantity: 1, unit: "pitada", category: "temperos" },
    ],
    steps: [
      "Marinar as coxas com sumo de 1 limão, alho esmagado, orégãos, azeite, sal e pimenta (30 min+).",
      "Pré-aquecer o forno a 200°C.",
      "Cortar as batatas em quartos e dispor no tabuleiro. Temperar com azeite e sal.",
      "Colocar as coxas sobre as batatas, com a pele para cima.",
      "Cortar o outro limão em rodelas e distribuir pelo tabuleiro.",
      "Assar 30 min até a pele ficar crocante e dourada. Regar com o molho do tabuleiro ao servir.",
    ],
    nutrition: { calories: 430, carbs: 32, protein: 30, fat: 20, fiber: 3 },
    tags: ["tradicional", "um-tabuleiro"],
  },
  {
    id: "bowl-salmao-abacate",
    name: "Bowl de Salmão e Abacate",
    description: "Bowl inspirado em poke hawaiano mas com ingredientes do supermercado. Saudável, bonito e saciante. O abacate maduro é essencial — deve ceder ligeiramente ao pressionar.",
    servings: 2,
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    mealType: ["almoco"],
    ingredients: [
      { name: "Salmão fresco", quantity: 200, unit: "g", category: "talho-peixaria" },
      { name: "Arroz", quantity: 150, unit: "g", category: "mercearia" },
      { name: "Abacate", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Pepino", quantity: 0.5, unit: "unidade", category: "frutas-legumes" },
      { name: "Edamame ou ervilhas", quantity: 50, unit: "g", category: "congelados" },
      { name: "Molho de soja", quantity: 2, unit: "colheres de sopa", category: "mercearia" },
      { name: "Limão", quantity: 0.5, unit: "unidade", category: "frutas-legumes" },
      { name: "Sementes de sésamo", quantity: 1, unit: "colher de chá", category: "mercearia" },
    ],
    steps: [
      "Cozer o arroz e temperar com um fio de vinagre de arroz ou limão (fica tipo sushi).",
      "Cortar o salmão em cubos de ~2cm. Marinar com molho de soja e sumo de limão 10 min.",
      "Cortar o abacate em fatias e o pepino em meias-luas finas.",
      "Cozer o edamame/ervilhas 3 min em água a ferver.",
      "Montar os bowls: arroz na base, dispor salmão, abacate, pepino e edamame por cima.",
      "Regar com molho de soja e polvilhar com sementes de sésamo.",
    ],
    nutrition: { calories: 420, carbs: 45, protein: 25, fat: 16, fiber: 5 },
    tags: ["saudável", "peixe"],
  },
  {
    id: "gratinado-legumes",
    name: "Gratinado de Legumes com Ovo",
    description: "Tabuleiro de legumes gratinados com ovo por cima — simples e reconfortante. Usa o que tiveres no frigorífico. Ideal para aproveitar sobras de legumes.",
    servings: 2,
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    mealType: ["jantar"],
    ingredients: [
      { name: "Curgete", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Pimento vermelho", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Cebola", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Tomate", quantity: 2, unit: "unidades", category: "frutas-legumes" },
      { name: "Ovos", quantity: 3, unit: "unidades", category: "lacticinios" },
      { name: "Azeite", quantity: 2, unit: "colheres de sopa", category: "mercearia" },
      { name: "Orégãos", quantity: 1, unit: "colher de chá", category: "temperos" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
    ],
    steps: [
      "Pré-aquecer o forno a 200°C.",
      "Cortar todos os legumes em rodelas ou meias-luas. Temperar com azeite, sal e orégãos.",
      "Dispor num tabuleiro/travessa de forno. Assar 15 min.",
      "Retirar, fazer 3 buracos nos legumes e partir um ovo em cada buraco.",
      "Voltar ao forno mais 8-10 min até as claras ficarem firmes (gema pode ficar cremosa).",
      "Servir diretamente do tabuleiro com pão para acompanhar.",
    ],
    nutrition: { calories: 260, carbs: 14, protein: 16, fat: 16, fiber: 4 },
    tags: ["leve", "vegetariano", "um-tabuleiro"],
  },
  {
    id: "arroz-pato-simples",
    name: "Arroz de Pato Simplificado",
    description: "Versão mais simples do clássico arroz de pato. Usa coxas de pato que são mais fáceis de encontrar e desfia. O toque final de gratinar no forno faz toda a diferença.",
    servings: 4,
    prepTimeMinutes: 15,
    cookTimeMinutes: 40,
    mealType: ["almoco"],
    ingredients: [
      { name: "Coxas de pato", quantity: 2, unit: "unidades", category: "talho-peixaria" },
      { name: "Arroz", quantity: 250, unit: "g", category: "mercearia" },
      { name: "Chouriço", quantity: 1, unit: "unidade", category: "talho-peixaria" },
      { name: "Cebola", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Cenoura", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Alho", quantity: 2, unit: "dentes", category: "frutas-legumes" },
      { name: "Louro", quantity: 2, unit: "folhas", category: "temperos" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
      { name: "Azeite", quantity: 2, unit: "colheres de sopa", category: "mercearia" },
    ],
    steps: [
      "Cozer as coxas de pato em água com cebola, cenoura, alho e louro ~30 min.",
      "Retirar o pato, desfiar a carne e guardar o caldo (coar).",
      "Refogar cebola picada no azeite. Juntar o arroz lavado.",
      "Adicionar o caldo coado (medida: 2x o volume do arroz). Cozer 15 min em lume brando.",
      "Juntar o pato desfiado e transferir para um tabuleiro de forno.",
      "Dispor rodelas de chouriço por cima e gratinar no forno a 220°C por 10 min até dourar.",
    ],
    nutrition: { calories: 480, carbs: 45, protein: 28, fat: 20, fiber: 2 },
    tags: ["tradicional", "reconfortante"],
  },
  {
    id: "poke-atum-lata",
    name: "Poke Bowl de Atum em Lata",
    description: "Versão económica do poke bowl com atum de lata em vez de fresco. Rápido, saudável e sem cozinhar quase nada. Ideal para dias quentes ou quando tens pressa.",
    servings: 2,
    prepTimeMinutes: 10,
    cookTimeMinutes: 12,
    mealType: ["almoco", "jantar"],
    ingredients: [
      { name: "Atum em lata", quantity: 2, unit: "latas", category: "mercearia" },
      { name: "Arroz", quantity: 150, unit: "g", category: "mercearia" },
      { name: "Pepino", quantity: 0.5, unit: "unidade", category: "frutas-legumes" },
      { name: "Cenoura", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Abacate", quantity: 0.5, unit: "unidade", category: "frutas-legumes" },
      { name: "Molho de soja", quantity: 2, unit: "colheres de sopa", category: "mercearia" },
      { name: "Limão", quantity: 0.5, unit: "unidade", category: "frutas-legumes" },
      { name: "Sementes de sésamo", quantity: 1, unit: "colher de chá", category: "mercearia" },
    ],
    steps: [
      "Cozer o arroz e deixar arrefecer ligeiramente. Temperar com sumo de limão.",
      "Escorrer o atum e desfiar grosseiramente.",
      "Ralar ou cortar a cenoura em palitos finos. Cortar o pepino em meias-luas.",
      "Cortar o abacate em fatias.",
      "Montar: arroz na base do bowl, dispor atum, legumes e abacate por cima.",
      "Regar com molho de soja e polvilhar com sésamo. Servir fresco.",
    ],
    nutrition: { calories: 380, carbs: 42, protein: 26, fat: 12, fiber: 4 },
    tags: ["rápido", "económico", "sem-cozinhar"],
  },

  // =============================================
  // === SNACKS ===
  // =============================================
  {
    id: "snack-ovo-cozido",
    name: "Ovos Cozidos com Palitos de Cenoura",
    description: "Snack proteico e sem hidratos — ideal para quando a glicemia está alta. Prepara ovos cozidos ao domingo e tens snack para a semana toda (duram 5 dias no frio).",
    servings: 1,
    prepTimeMinutes: 1,
    cookTimeMinutes: 10,
    mealType: ["snack"],
    ingredients: [
      { name: "Ovos", quantity: 2, unit: "unidades", category: "lacticinios" },
      { name: "Cenoura", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
    ],
    steps: [
      "Cozer os ovos 10 minutos em água a ferver (começar com água fria ajuda a não partirem).",
      "Arrefecer em água fria e gelo 5 min (descascam muito mais fácil assim).",
      "Descascar a cenoura e cortar em palitos.",
      "Temperar os ovos com uma pitada de sal e servir com a cenoura.",
    ],
    nutrition: { calories: 170, carbs: 5, protein: 13, fat: 11, fiber: 2 },
    tags: ["snack", "proteico", "sem-hidratos", "rápido"],
  },
  {
    id: "snack-iogurte-nozes",
    name: "Iogurte Natural com Nozes",
    description: "Snack leve e saciante. Usa iogurte natural sem açúcar — as nozes dão gorduras boas e a combinação mantém a glicemia estável.",
    servings: 1,
    prepTimeMinutes: 2,
    cookTimeMinutes: 0,
    mealType: ["snack"],
    ingredients: [
      { name: "Iogurte natural", quantity: 1, unit: "unidade", category: "lacticinios" },
      { name: "Nozes", quantity: 15, unit: "g", category: "mercearia" },
    ],
    steps: [
      "Colocar o iogurte numa taça.",
      "Partir as nozes grosseiramente com as mãos e colocar por cima.",
      "Dica: podes adicionar uma pitada de canela para variar (e a canela ajuda a estabilizar glicemia).",
    ],
    nutrition: { calories: 150, carbs: 8, protein: 6, fat: 10, fiber: 1 },
    tags: ["snack", "rápido", "sem-cozinhar"],
  },
  {
    id: "snack-queijo-fresco-tomate",
    name: "Queijo Fresco com Tomate e Orégãos",
    description: "Snack simples e leve — bom quando a glicemia está acima do ideal. Tipo caprese portuguesa.",
    servings: 1,
    prepTimeMinutes: 3,
    cookTimeMinutes: 0,
    mealType: ["snack"],
    ingredients: [
      { name: "Queijo fresco", quantity: 1, unit: "unidade", category: "lacticinios" },
      { name: "Tomate", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Azeite", quantity: 1, unit: "fio", category: "mercearia" },
      { name: "Orégãos", quantity: 1, unit: "pitada", category: "temperos" },
    ],
    steps: [
      "Cortar o tomate em rodelas.",
      "Servir com o queijo fresco, um fio de azeite e orégãos.",
      "Dica: um toque de flor de sal por cima eleva o sabor.",
    ],
    nutrition: { calories: 120, carbs: 5, protein: 8, fat: 7, fiber: 1 },
    tags: ["snack", "sem-cozinhar", "baixo-hidrato"],
  },
  {
    id: "snack-hummus-legumes",
    name: "Hummus com Palitos de Legumes",
    description: "Hummus caseiro em 5 min! Muito mais barato e saboroso que comprado. O tahini é opcional mas faz diferença. Mergulha palitos de legumes crus.",
    servings: 2,
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    mealType: ["snack"],
    ingredients: [
      { name: "Grão-de-bico (lata)", quantity: 240, unit: "g", category: "mercearia" },
      { name: "Tahini (pasta de sésamo)", quantity: 1, unit: "colher de sopa", category: "mercearia" },
      { name: "Limão", quantity: 0.5, unit: "unidade", category: "frutas-legumes" },
      { name: "Alho", quantity: 1, unit: "dente", category: "frutas-legumes" },
      { name: "Pepino", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Cenoura", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Azeite", quantity: 1, unit: "colher de sopa", category: "mercearia" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
    ],
    steps: [
      "Triturar o grão escorrido com tahini, limão, alho, azeite e sal no liquidificador/varinha.",
      "Se ficar muito espesso, juntar 1-2 colheres de água até ficar cremoso.",
      "Cortar pepino e cenoura em palitos.",
      "Servir o hummus com os legumes para mergulhar. Guarda no frio até 5 dias.",
    ],
    nutrition: { calories: 180, carbs: 18, protein: 8, fat: 9, fiber: 5 },
    tags: ["snack", "sem-cozinhar", "saudável"],
  },
  {
    id: "snack-maca-manteiga-amendoim",
    name: "Maçã com Manteiga de Amendoim",
    description: "Snack equilibrado com hidratos lentos e gordura boa. Ideal quando a glicemia está normal ou ligeiramente baixa. A manteiga de amendoim trava o pico de glicemia da fruta.",
    servings: 1,
    prepTimeMinutes: 2,
    cookTimeMinutes: 0,
    mealType: ["snack"],
    ingredients: [
      { name: "Maçã", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Manteiga de amendoim", quantity: 1, unit: "colher de sopa", category: "mercearia" },
    ],
    steps: [
      "Cortar a maçã em fatias (com ou sem casca — a casca tem mais fibra).",
      "Barrar ou mergulhar na manteiga de amendoim.",
      "Dica: escolhe manteiga de amendoim SEM açúcar adicionado (ingrediente: apenas amendoins e sal).",
    ],
    nutrition: { calories: 200, carbs: 22, protein: 5, fat: 10, fiber: 4 },
    tags: ["snack", "rápido", "sem-cozinhar"],
  },
  {
    id: "snack-frutos-secos",
    name: "Mix de Frutos Secos",
    description: "Porção controlada (~30g) de frutos secos. Muito saciante mas calórico — não exagerar na quantidade. Ideal para levar na mala quando sais de casa.",
    servings: 1,
    prepTimeMinutes: 0,
    cookTimeMinutes: 0,
    mealType: ["snack"],
    ingredients: [
      { name: "Amêndoas", quantity: 10, unit: "g", category: "mercearia" },
      { name: "Nozes", quantity: 10, unit: "g", category: "mercearia" },
      { name: "Cajus", quantity: 10, unit: "g", category: "mercearia" },
    ],
    steps: [
      "Misturar os frutos secos numa taça pequena ou saco.",
      "Dica: pesa e prepara porções individuais ao domingo para não comeres demais durante a semana.",
    ],
    nutrition: { calories: 170, carbs: 6, protein: 5, fat: 15, fiber: 2 },
    tags: ["snack", "sem-cozinhar", "baixo-hidrato"],
  },
  {
    id: "snack-tosta-abacate",
    name: "Tosta de Abacate e Ovo",
    description: "Snack mais substancial para quando tens fome a sério entre refeições. O abacate dá gordura boa e o ovo proteína. Usa pão integral para mais fibra.",
    servings: 1,
    prepTimeMinutes: 5,
    cookTimeMinutes: 5,
    mealType: ["snack"],
    ingredients: [
      { name: "Pão integral", quantity: 1, unit: "fatia", category: "padaria" },
      { name: "Abacate", quantity: 0.5, unit: "unidade", category: "frutas-legumes" },
      { name: "Ovo", quantity: 1, unit: "unidade", category: "lacticinios" },
      { name: "Sal", quantity: 1, unit: "pitada", category: "temperos" },
      { name: "Pimenta", quantity: 1, unit: "pitada", category: "temperos" },
    ],
    steps: [
      "Tostar o pão na torradeira ou frigideira seca.",
      "Esmagar o abacate com um garfo e espalhar sobre a tosta.",
      "Fritar ou escalfar o ovo e colocar por cima.",
      "Temperar com sal e pimenta. Opcional: flocos de malagueta para dar um kick.",
    ],
    nutrition: { calories: 250, carbs: 18, protein: 10, fat: 16, fiber: 5 },
    tags: ["snack", "rápido", "proteico"],
  },
  {
    id: "snack-banana-canela",
    name: "Banana com Canela",
    description: "Snack rápido com hidratos naturais — ideal para glicemia baixa ou antes de exercício. A canela ajuda a regular a absorção de açúcar.",
    servings: 1,
    prepTimeMinutes: 1,
    cookTimeMinutes: 0,
    mealType: ["snack"],
    ingredients: [
      { name: "Banana", quantity: 1, unit: "unidade", category: "frutas-legumes" },
      { name: "Canela", quantity: 1, unit: "pitada", category: "temperos" },
    ],
    steps: [
      "Descascar a banana e cortar em rodelas.",
      "Polvilhar com canela.",
      "Dica: se a glicemia estiver baixa, come a banana inteira — os açúcares naturais atuam rápido.",
    ],
    nutrition: { calories: 105, carbs: 27, protein: 1, fat: 0, fiber: 3 },
    tags: ["snack", "rápido", "sem-cozinhar"],
  },
];

export function getRecipeById(id: string): Recipe | undefined {
  return RECIPES.find((r) => r.id === id);
}

export function getRecipesByMealType(mealType: string): Recipe[] {
  return RECIPES.filter((r) => r.mealType.includes(mealType as Recipe["mealType"][number]));
}
